---
kind: pipeline
name: lk2nd-msm8916

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh lk2nd-msm8916]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: lk2nd-msm8974

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh lk2nd-msm8974]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: lk2nd-msm8226

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh lk2nd-msm8226]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: lk2nd-msm8909

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh lk2nd-msm8909]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: msm8916

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh msm8916]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: msm8974

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh msm8974]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: msm8226

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh msm8226]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: msm8909

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh msm8909]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: lk1st-msm8916

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh lk1st-msm8916]

trigger:
  event: [push, pull_request, tag]
---
kind: pipeline
name: lk1st-msm8916-db410c

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: debian:buster
    commands: [./.drone.sh lk1st-msm8916 FORCE_SDCARD=1 LK1ST_DTB=apq8016-sbc LK1ST_PANEL=adv7533_1080p_video]

trigger:
  event: [push, pull_request, tag]
